//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.WindowsDesktop.DataAccess.Net40.Models
{
    using System;
    using System.Collections.Generic;

    internal partial class GroupRole
    {
        public long MusicianID { get; set; }
        public long ArtistID { get; set; }
        public System.DateTime GroupFormationDate { get; set; }
        public string MusicianRoleName { get; set; }
        public Nullable<System.DateTime> GroupJoinDate { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual GroupMember GroupMember { get; set; }
        public virtual MusicianRole MusicianRole { get; set; }
        public virtual Musician Musician { get; set; }
    }
}
