//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.WindowsDesktop.DataAccess.Net40.Models
{
    using System;
    using System.Collections.Generic;

    internal partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Administrators = new HashSet<Administrator>();
            this.ListenedAlbums = new HashSet<ListenedAlbum>();
            this.ListenedArtists = new HashSet<ListenedArtist>();
            this.ListenedCompositions = new HashSet<ListenedComposition>();
            this.ListenedGenres = new HashSet<ListenedGenre>();
            this.Moderators = new HashSet<Moderator>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfSignUp { get; set; }
        public string VKLink { get; set; }
        public string FaceBookLink { get; set; }
        public string Bio { get; set; }
        public Nullable<System.DateTime> LastListenedCompositionChange { get; set; }
        public Nullable<System.DateTime> LastListenEntitiesUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrator> Administrators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListenedAlbum> ListenedAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListenedArtist> ListenedArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListenedComposition> ListenedCompositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListenedGenre> ListenedGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moderator> Moderators { get; set; }
    }
}
