//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.DataAccess.Net40.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionVideo
    {
        public long VideoID { get; set; }
        public long ArtistID { get; set; }
        public long AlbumID { get; set; }
        public long CompositionID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Composition Composition { get; set; }
        public virtual Video Video { get; set; }
    }
}
