//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.DataAccess.Net40.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Composition()
        {
            this.CompositionVideos = new HashSet<CompositionVideo>();
            this.ListenedCompositions = new HashSet<ListenedComposition>();
        }
    
        public long CompositionID { get; set; }
        public string CompositionName { get; set; }
        public Nullable<long> ArtistID { get; set; }
        public Nullable<System.DateTime> GroupFormationDate { get; set; }
        public Nullable<long> AlbumID { get; set; }
        public Nullable<long> Duration { get; set; }
        public string FilePath { get; set; }
        public string Lyrics { get; set; }
        public string About { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual GroupMember GroupMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionVideo> CompositionVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListenedComposition> ListenedCompositions { get; set; }
    }
}
