//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.DataAccess.Net40
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MediaStreamer.Domain;
    
    public partial class mainEntities2 : DbContext
    {
        public mainEntities2()
            : base("name=mainEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<AlbumGenre> AlbumGenres { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistGenre> ArtistGenres { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<CompositionVideo> CompositionVideos { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        //public virtual DbSet<GroupMember> GroupMembers { get; set; }
        //public virtual DbSet<GroupRole> GroupRoles { get; set; }
        //public virtual DbSet<ListenedAlbum> ListenedAlbums { get; set; }
        //public virtual DbSet<ListenedArtist> ListenedArtists { get; set; }
        public virtual DbSet<ListenedComposition> ListenedCompositions { get; set; }
        //public virtual DbSet<ListenedGenre> ListenedGenres { get; set; }
        public virtual DbSet<Moderator> Moderators { get; set; }
        //public virtual DbSet<Musician> Musicians { get; set; }
        //public virtual DbSet<MusicianRole> MusicianRoles { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
